### ISSUE TITLE
Bin file for ota update

### ISSUE THREAD

**Issue by johannesbonn** [ascillato/Sonoff-Tasmota_KNX#40]
Hi,

Your work looks amazing. Can you please provide a bin file for the ota update?

Thank you

Johannes

**Comment by ascillato** [comment]
I just uploaded some binaries to release [v5.12.0k](https://github.com/ascillato/Sonoff-Tasmota_KNX/releases/tag/v5.12.0k)

The binaries provided are:

* **sonoff_KNX-EN.bin** (Tasmota version with KNX - English Version)
* **sonoff_KNX-ES.bin** (Tasmota version with KNX - Spanish Version)
* **sonoff_KNX-EN-4M.bin** (Tasmota version with KNX for 4M Devices - English Version)
* **sonoff_KNX-ES-4M.bin** (Tasmota version with KNX for 4M Devices - Spanish Version)

For other languages, the KNX is just in English by now. Needs translation on [language files](https://github.com/ascillato/Sonoff-Tasmota_KNX/tree/development/sonoff/language). If you need anything in particular just ask.

( For better performance is used MQTT_LIBRARY_TYPE = MQTT_TASMOTAMQTT )

( For better initial help is used WIFI_CONFIG_TOOL = WIFI_MANAGER )

( Binaries are also with the [Alexa Bug solved](https://github.com/arendst/Sonoff-Tasmota/issues/1639) )
