### ISSUE TITLE
KNX topology in order to use Tasmota KNX

### ISSUE THREAD

**Issue by avrandrei** [ascillato/Sonoff-Tasmota_KNX#584]
### PROBLEM DESCRIPTION
I have a KNX installation in my house. It's rather simple: everything is on one line, one area using a TP medium. In ETS everything is configured as TP from the backbone to the area and the line. I do have an IP Router but I've only used it for ETS programming and for integration my KNX system with Home Assistant.

Now I would like to use some Tasmota KNX devices with my network, but I'm no sure on how the KNX topology should look like. Should I configure the IP Router to be a backbone coupler? Do I need to have an additional Line coupler if I use the IP Router as the backbone coupler?

**Comment by ascillato** [comment]
https://github.com/arendst/Tasmota/discussions/13371
