### ISSUE TITLE
Problem sending KNX telegrams

### ISSUE THREAD

**Issue by Sansibari** [ascillato/Sonoff-Tasmota_KNX#597]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Sansibari** [comment]
I configured a D1 8266 as following:

![image](https://user-images.githubusercontent.com/48505288/236487493-2d5ef3d0-e2fa-4e34-bbce-b6c89a487d63.png)

I use a MDT IP Gateway and ETS6
Have no problem to communicate via Node-Red over Wifi to the KNX Bus.
But no messages are received from the Tasmota Device.
The ETS Group monitor shows:

![image](https://user-images.githubusercontent.com/48505288/236488299-4928e071-88dc-4f55-b432-7abff40b4ce2.png)
It seems, the DPT and Info is not received in the correct format.

Any ideas?
Thanks in advance!

**Comment by Sansibari** [comment]
![image](https://user-images.githubusercontent.com/48505288/236489618-1d6010c0-8db4-40ea-be20-bcf2bfafa6b5.png)

**Comment by Sansibari** [comment]
![image](https://user-images.githubusercontent.com/48505288/236490407-4ab274aa-f9cd-47f5-a1e7-83867a28a7b8.png)

**Comment by Sansibari** [comment]
![image](https://user-images.githubusercontent.com/48505288/236490577-49f5c644-844e-4d54-b7db-d1fa26536740.png)

**Comment by Sansibari** [comment]
![image](https://user-images.githubusercontent.com/48505288/236490853-329837cf-f540-4ef1-bbaa-4aa905377563.png)

**Comment by ascillato** [comment]
Hi, sorry to hear about your issue. Seems that your system is expecting the temperature in another format. Previously we were using that format but then we changed to a new one by users requests. Since we have received reports that some system uses the previous format we were thinking on adding an option to select the format in the UI. That requires some changes that at the moment I won't be able to work on. Hopefully in the future I have time to expand the KNX driver for Tasmota.
