### ISSUE TITLE
Need to change relay selection to output selection

### ISSUE THREAD

**Issue by arendst** [ascillato/Sonoff-Tasmota_KNX#68]
Make sure these boxes are checked before submitting your issue - Thank you!

- [ ] What hardware you are using
- [ ] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

Currently knx only allows for selecting a relay to be conttrolled and selected. Tasmota also supports lights wich do not show up as relay.

A device with only a light like a ws2812 currently cannot be controlled by knx

Suggestions:
Use the power variable together with devices_present to select an output as I did in timers.ino. Also use the name output as in timers.ino as it is already translated.

When you dig around you'll find that a light will always be the highest power bit.

**Comment by ascillato** [comment]
Ok, Thanks. working....

**Comment by ascillato** [comment]
Done. :smile:

Thanks a lot for the hint :+1:
